### PR TITLE
fix: saved terminal status corruption

### LINKED ISSUE #594: CentOS7.6部署v1.2.0使用ts-cli输入认证信息无反应且无法认证成功
### Describe the bug（Bug 描述）

使用社区二进制版本openGemini-1.2.0-linux-amd64在CentOS Linux release 7.6. 上部署成功后，使用自带的ts-cli工具集群认证，连接使用输入用户名无反应，多次输入回车命令行界面显示异常，退出ts-cli后发现Linux shell 回车也会显示异常，经测试目前使用v1.1.1正常。如下图：
image

社区其他群友反馈，,windows上使用正常，银河麒麟 4.19.90-52.22.v2207.ky10.x86_64使用和CentOS 7.6 异常信息一致，使用不正常，如下图：
image

### To Reproduce（Bug 复现步骤）

1. 使用二进制版本（openGemini-1.2.0-linux-amd64）部署
2. 使用ts-cli连接集群
3. 使用auth命令进行认证，回车再现问题

### Expected behavior（期望结果）

使用ts-cli连接集群，auth命令进行认证正常，访问集群正常

### Screenshots（屏幕截图）

image

### Logs（完整的错误日志）

_No response_

### Additional context（其他的一些补充内容）

_No response_

### PR DESCRIPTION
**Pull request by StepY1aoZz**
fix https://github.com/openGemini/openGemini/issues/594.

When the `saveTermios` variable (referring the original terminal state) is a pointer, it will be modified unexpectedly in function `SetRaw` (should be the original state, but becomes the modified 'raw' state), which leads to the `Restore` function not really working.

### CODE REVIEW

File: internal/term/raw.go [hunk 1]
```diff
@@ -25,5 +25,5 @@ func SetRaw(fd int) error {
 	n.Cc[syscall.VMIN] = 1
```
Comment (xuthus5) [inline internal/term/raw.go:25]: change go module name to `openGemini/go-prompt`

Comment (StepY1aoZz) [reply internal/term/raw.go:25]: Done

> change go module name to `openGemini/go-prompt`

**Comment by xuthus5** [comment]
this change worked for me on `EulerOS/bash`.

**Comment by xuthus5** [comment]
cc @xiangyu5632
